shiny:
  proxy:
    title: Gerrymandering Texas
    logo-url: https://drive.google.com/uc?export=view&id=1fauCF5_81llAgcE26DCGoTm02Rfrg2Ac
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    container-wait-time: 30000
    port: 8080
    authentication: social
    social:
      google:
        app-id: 109365349953-6isj32t7hjojludfdsv9lgq77kc34sd9.apps.googleusercontent.com
        app-secret: vpuc-GFQckA2JIYopsP7fsNG
      twitter:
        app-id: BdsHTBH4bCZsWcCQiYz1vIH66
        app-secret: sI0cWiK1zKiBlcqCYtULFUbtKkEozjXoUnXh7HetAq4NIDHTth
    docker:
      url: http://localhost:2375
      port-range-start: 30000
  apps:
  - name: gerrys_world_01
    display-name: Gerry's World
    description: Gerrymandering
    docker-cmd: ["R","-e shiny::runApp('/root/gerrys_world',port=3838,host='0.0.0.0')"]
    docker-image: gerrys_world.dev
    #docker-image: velaraptor/gerrys_world
logging:
  file:
    shinyproxy.log
